name: Release

on:
  release:
    types: [published]

env:
  BUILD_TYPE: Release

jobs:
  build-and-upload:
    name: Build and Upload to Release - Windows
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - run: Get-Command vcpkg

      - name: vcpkg install
        run: vcpkg install libtorrent:x64-windows-static --classic

      - name: Configure CMake
        run: |
          $env:VCPKG_ROOT = "C:\vcpkg\"
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja -DCMAKE_CXX_COMPILER=clang-cl

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{github.workspace}}/build/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
